### ISSUE TITLE
Write Unit Tests for `get_modification_time` Method

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#1]
- **Description**: Write tests to validate the `get_modification_time` method in the `AllFileMetadata` class. Test cases should include scenarios where:
  - The file exists, and the modification time is returned.
  - The file does not exist, and the method returns `-1`.
- **Resources**: Use the [pytest getting started guide](https://docs.pytest.org/en/stable/getting-started.html) to set up your tests.
- **Path**: `twinTrim/dataStructures/allFileMetadata.py`
- **Code to be added**: `tests`
- **Note**: Ensure to maintain the file structure as per the existing files and tests.

**Comment by ohmschrodinger** [comment]
can you assign it to me?

**Comment by SaanyaGarg5** [comment]
you can assign that task to me..

**Comment by Kota-Karthik** [comment]
@SaanyaGarg5 
Its already assigned to someone else
You can check other issues which are not assigned to anyone 
or you can even create a new issue , if you want to fix a bug or add feature or even if you want to improve UI
