### ISSUE TITLE
Test Thread-Safety of `add_or_update_normal_file`

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#10]
- **Description**: Write tests that simulate multiple threads calling the `add_or_update_normal_file` function concurrently. Ensure that the `normalStore` maintains consistency under concurrent access.
   - **Resources**: Use the [pytest guide](https://docs.pytest.org/en/stable/getting-started.html) to write tests for thread-safety and locking mechanisms.
   - **Path**: `twinTrim/dataStructures/fileMetadata.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

**Comment by tarunkumar2005** [comment]
@Kota-Karthik I would like to work on it. Assign me under GSSOC2024 ext and hacktoberfest.

**Comment by Kota-Karthik** [comment]
@tarunkumar2005 
Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by tarunkumar2005** [comment]
@Kota-Karthik there already exists a file on the path you defined :- twinTrim/dataStructures/fileMetadata.py

**Comment by Kota-Karthik** [comment]
@tarunkumar2005 
That is where the code exists and you need to write tests in a new file named fileMetadata in tests folder

**Comment by tarunkumar2005** [comment]
@Kota-Karthik I have completed the tests check i have created the pull request Review it and add labels to the request :- gssoc ext and hacktoberfest.
