### ISSUE TITLE
Add Logging and Reports

### ISSUE THREAD

**Issue by Riya7045** [Kota-Karthik/twinTrim#108]
Current Implementation: TwinTrim provides feedback via command-line prompts.

Proposed Change: Add a logging feature to track actions taken, such as deleted files, scan results, and errors. Also, could you generate a summary report of the duplicates found, retained, or deleted in CSV or PDF format?

How to Implement: Use the logging module to create detailed logs and implement a reporting function to generate CSV or PDF summaries of duplicate file management actions.

please add label gssoc-ext24,hacktoberfest and level 1,level2 and level 3 @Kota-Karthik

**Comment by Wahid7852** [comment]
1. Why would we add a logger to create logs when we are not debugging the application.
2. Summary report sounds nice but we do it already....

Our tool is meant to be cli based
if we improve the cli output, then it sounds better but if we just export it out then nah...

**Comment by techy4shri** [comment]
While this feature sounds great here, if you look at the code, an the project, we are not looking to add any complexities to the package. This is a python package, meant to simplify the task of users through a simple CLI. 
Kindly read the documentation present in the repository, i.e. the docs and proceed with raising issues accordingly.
