### ISSUE TITLE
[Enhancement] Update README to add contributors automatically 

### ISSUE THREAD

**Issue by jvkousthub** [Kota-Karthik/twinTrim#109]
**Describe the enhancement**
Readme can be updated to add all the contributors automatically .

**Why is this enhancement necessary?**
There should be some value given to their contributions.

**Proposed solution**
Generate a link of image that manages to add contributors automatically .

**Alternatives considered**
If applicable, mention any alternative solutions you've considered.

**Additional context**
Add any other context or screenshots related to the enhancement here.

**Comment by jvkousthub** [comment]
@Kota-Karthik assign me with the issue

**Comment by techy4shri** [comment]
No readme issues allowed. We value our contributors enough. This issue will be closed on account of being redundant and void. This is your first warning.
