### ISSUE TITLE
 Mock File Operations in `add_or_update_normal_file`

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#11]
- **Description**: Mock file operations (like file access) in the `add_or_update_normal_file` tests to simulate various file system behaviors, including files that exist and files that do not. This ensures the function behaves as expected without relying on the actual file system.
   - **Resources**: Refer to the [pytest mocking section](https://docs.pytest.org/en/stable/getting-started.html) for instructions on mocking file access operations.
   - **Path**: `twinTrim/dataStructures/fileMetadata.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

**Comment by SandyK1002** [comment]
Can I work on this issue?

**Comment by Kota-Karthik** [comment]
@SandyK1002 
Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by KartikSaxena19** [comment]
You can assign this task to me

**Comment by techy4shri** [comment]
@KartikSaxena19 let's wait for tonight, if Sandeep  does not respond, you will be assigned to this issue.

**Comment by KartikSaxena19** [comment]
I will try my best to resolve this issue within 1 or 2 days if I complete this issue in the given time period than please assign compare and replace issue to me

**Comment by JahnaviDhanaSri** [comment]
Hello can you please assign this issue to me

**Comment by techy4shri** [comment]
@JahnaviDhanaSri This is the 3rd time I am seeing you commenting on an assigned issue which also has a recently made PR.
This is your forst warning, either raise issues on your own or you won't be assigned unless the issue is currently not assigned to someone else.

**Comment by JahnaviDhanaSri** [comment]
Ok

**Comment by ShirshenduR** [comment]
assign me this issue

**Comment by Kota-Karthik** [comment]
@JahnaviDhanaSri 
Do you still want to work on this issue?

**Comment by Jasmeetkaur-13** [comment]
Could you please assign me to the task of writing unit tests for the setMinFileSize method? I'm ready to begin implementing the tests according to the guidelines.

**Comment by lakshyaog** [comment]
@Kota-Karthik you can assign this task to me  i can help .

**Comment by Kota-Karthik** [comment]
@lakshyaog 
make sure to create a separate branch before making the necessary changes and retain the folder structure
strictly follow PR template before raising any PR.

**Comment by lakshyaog** [comment]
Okk thank u

**Comment by Kota-Karthik** [comment]
@lakshyaog 
any updates ?
are you working on this ?
reply by EOD , else i will be unassigning you !

**Comment by lakshyaog** [comment]
Sorry to say but u can assign to anyother thank u for your assign

**Comment by yashksaini-coder** [comment]
I want to work on this issue @Kota-Karthik

**Comment by ShirshenduR** [comment]
> This issue is now open to all. Whoever replies to me first will be assigned.

Assign me

**Comment by techy4shri** [comment]
@ShirshenduR you are assigned.
