### ISSUE TITLE
[Workflow] Automated Greetings and Label assignment Workflow

### ISSUE THREAD

**Issue by decodingafterlife** [Kota-Karthik/twinTrim#110]
**Problem**
Sometimes a large number of issues and features may be added by open-source contributors and users. This may lead to the admins being overwhelmed to add labels, allocate and handle all of the issues raised. The solution focuses on automating some part of these process so that admins can focus only on the important that need their attention.

**Proposed changes**
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

There will be another GitHub workflow named Auto-Label which would scan the title of the raised issue and assign appropriate labels. Specific labels or other requirements suggested by the admins can be integrated in this.

I wish to contribute this through GSSoC-ext and Hacktoberfest

**Comment by Kota-Karthik** [comment]
No , thanks
This will really create much chaos than helping 
Might assign a level3 to level1 issue

**Comment by techy4shri** [comment]
This project focuses on low level issues which require extensive insight. Due to this issue being nonsubstantive we are closing this at the moment.

**Comment by Wahid7852** [comment]
1. The PA / mentors of this repo are fairly active while maintaining this repo. 
2. Automation is going to be a headache if a single mistake happens. 

Taking the words of @techy4shri into consideration, closing it.
