### ISSUE TITLE
[Documentation] Improve README File for TwinTrim Project

### ISSUE THREAD

**Issue by T-Fathima** [Kota-Karthik/twinTrim#113]
**What documentation needs to be updated?**
The README file for the twinTrim project requires improvements to enhance clarity and usability for new users.

**Describe the changes needed**
Add a Table of Contents
Contact Information
Enhance Section Titles
Make the README file more visually interactive

**Additional context**
Implementing these changes will make the README more user-friendly and improve overall project documentation, helping users get started quickly and effectively.

I would like to work on this.
@Kota-Karthik Please assign this issue to me under gssoc-ext and hacktoberfest.

**Comment by techy4shri** [comment]
We do not accept readme issues. Read the dcouments forst before raising issues.
