### ISSUE TITLE
Add Unit Tests for Improved Reliability

### ISSUE THREAD

**Issue by NismaK** [Kota-Karthik/twinTrim#114]
Hi there! I noticed that the project currently lacks unit tests, which are essential for ensuring the reliability of the code. Implementing tests for the core functionalities would help catch bugs early and improve overall quality. Additionally, having a tests directory with examples of how to run the tests would be beneficial for contributors. Let me know if you’d like assistance in creating these tests!

**Comment by ShashwatAgrawal20** [comment]
hey @NismaK, the test cases are already present in the project, I don't think you've seen the project yet.

@Kota-Karthik @techy4shri 

Sorry

![dontneedtoaddress](https://github.com/user-attachments/assets/8fad7c48-b320-4eac-a1c5-085367a8e7ea)


**CLOSING**

**Comment by techy4shri** [comment]
@ShashwatAgrawal20 please do not use gifs here...........
