### ISSUE TITLE
[Documentation] Update README file by adding Table of Contents

### ISSUE THREAD

**Issue by Maryam0330** [Kota-Karthik/twinTrim#115]
**What documentation needs to be updated?**
I want to add the `Table of Contents` section to the README.md file.

**Describe the changes needed**
Adding a `Table of Contents` section to the README file will enhance navigation and provide a more user-friendly experience for end users. It will allow for quick access to key sections and improve the overall readability of the project.

**Comment by Maryam0330** [comment]
Please assign me this task under `gssoc-ext` and `hacktoberfest-accepted` label.

**Comment by Kota-Karthik** [comment]
@Maryam0330 
make sure to create a separate branch before making the necessary changes and retain the folder structure.
Please follow the PR template while making a PR

**Comment by techy4shri** [comment]
While this endeavor may be designated and embraced under the auspices of Hacktoberfest, we must categorically state that we cannot acquiesce to README-related issues within the framework of GSSOC-EXT. Consequently, this issue will be exclusively designated with the Hacktoberfest label.

**Comment by techy4shri** [comment]
Done! @Kota-Karthik
