### ISSUE TITLE
[Feature] Log file creation

### ISSUE THREAD

**Issue by anishka25** [Kota-Karthik/twinTrim#119]
Users may face confusion over which files were deleted or retained during duplicate management, leading to potential data loss and a lack of accountability for actions taken by the tool.

I would like to add log file creation functionality so that the user can keep track of what files were identified, deleted, or kept.

**Comment by Kota-Karthik** [comment]
@anishka25 
If you are raising such an issue 
This clearly shows that you totally haven't gone through the project implementation and you haven't even used it !
We recommend you to read docs and use project before raising any such issues!
I am closing this!
Thank you for your interest!
