### ISSUE TITLE
 Write Unit Tests for `setMinFileSize` Method

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#12]
- **Description**: Write unit tests to validate the behavior of the `setMinFileSize` method. Ensure that it correctly sets the minimum file size and that it can handle invalid inputs.
   - **Resources**: Refer to the [pytest getting started guide](https://docs.pytest.org/en/stable/getting-started.html) for setting up tests.
   - **Path**: `twinTrim/dataStructures/fileFilter.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

**Comment by kushwxha** [comment]
can you please assign this issue to me??

**Comment by Kota-Karthik** [comment]
@kushwxha 
Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by Kota-Karthik** [comment]
@kushwxha, 
please check the review I left on the PR. It’s also a good practice to mention 'Fixes #<issue number>' in the PR.

**Comment by kushwxha** [comment]
hey @Kota-Karthik, can you check this pr #32 and review it

**Comment by kushwxha** [comment]
hey @Kota-Karthik, 
i have resolved the conflict of this issue also. can you check it now? and please add the labels to the pr.

**Comment by harshitpathak528** [comment]
I can make it more better can you also assign me.

**Comment by Kota-Karthik** [comment]
@kushwxha 
I am unassigning you 
@harshitpathak528 
yes, you can work on it 
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by harshitpathak528** [comment]
Sure, I already start working on it.

**Comment by harshitpathak528** [comment]
I raised the PR please check it out

**Comment by JahnaviDhanaSri** [comment]
Hello can you please assign this issue to me

**Comment by techy4shri** [comment]
@JahnaviDhanaSri you can work on it.

**Comment by Kota-Karthik** [comment]
@JahnaviDhanaSri 
do you still want to work on this?

**Comment by techy4shri** [comment]
This project demands a rigorous approach to low-level issues that require both substantial insight and clarity. It is imperative that you provide additional context along with relevant use cases, as generic or overly simplistic responses will not meet our standards.
Failure to adhere to these expectations may affect your standing in this project.

In simple words: the gippity is pouring from this dear, I advise you against it.

**Comment by Kajalkansal30** [comment]
I will surely take this in mind while submitting to share my code for issue.
I am eager to take on the challenge of writing unit tests for the setMinFileSize method, and I would be appreciated to be assigned to this issue.

**Comment by techy4shri** [comment]
@smartfellow1234 explain your approach.

**Comment by Jasmeetkaur-13** [comment]
Could you please assign me to the task of writing unit tests for the method? I’m ready to get started on implementing the tests as per the guidelines.

**Comment by techy4shri** [comment]
@smartfellow1234 you are assigned. create a new branch and start working on it. You have 3 days to make a PR for this!

**Comment by techy4shri** [comment]
@smartfellow1234 mention this issue in your PR and follow the template format.

**Comment by techy4shri** [comment]
@smartfellow1234, please be advised that we are subject to human limitations, and thorough reviews require adequate time. Furthermore, it is not feasible for us to provide daily availability for this task.
