### ISSUE TITLE
[Documentation] Enhancement of Readme.md

### ISSUE THREAD

**Issue by khushidadwal** [Kota-Karthik/twinTrim#123]
**What documentation needs to be updated?**
 I would like to update the current readme file.

**Describe the changes needed**
The current file looks very simple and dull . I would like to add some icons to make it look more attractive and interacting.

Please assign this task to me.
Thanks :-)

**Comment by Kota-Karthik** [comment]
@khushidadwal 
We do not encourage `Documentation` related issues
