### ISSUE TITLE
Lack of Backup Option Before Deleting Duplicate Files

### ISSUE THREAD

**Issue by Aditya-kr-01** [Kota-Karthik/twinTrim#124]
Description & Solution:
Currently, TwinTrim doesn’t have a way to back up files before deleting them, which can be risky. If a user accidentally deletes something important while cleaning duplicates, there’s no way to get it back. This can cause frustration, especially when dealing with a large number of files. Without a backup option, users might hesitate to use the tool fully.

A simple solution would be to add a backup feature. Before deleting any duplicates, the tool could move them to a separate folder where users can review and restore them if needed. This backup folder could be automatically cleared after a certain amount of time to save space. Adding this option would help users feel more secure about using the tool, knowing they have a safety net if they delete something by mistake.

Alternate Solution & Fix:
One way to avoid accidental file deletion is to add a "soft delete" feature instead of a full backup. Instead of permanently deleting duplicates right away, TwinTrim could move them to a "Recycle Bin" or a temporary holding area. Files in this holding area would only be deleted after a certain period, giving users time to review and recover them if needed.

This approach would be simpler than a full backup system, as it doesn’t require extra storage space or manual backups. Users would still have a safety net, but without the complexity of managing backup folders. By keeping the process clean and automatic, the risk of losing important files would be reduced, while still making the cleanup process easy and efficient .

**Comment by Kota-Karthik** [comment]
@Aditya-kr-01 
before raising such issues i suggest you to go through other issues in this project
a similar issue was raised and was closed by us!
cause we feel that this enhancement isn't really neccessary
