### ISSUE TITLE
[Documentation] README FILE NEEDS TO BE CHANGED

### ISSUE THREAD

**Issue by ABHISIKTAcommits** [Kota-Karthik/twinTrim#125]
**What documentation needs to be updated?**
README FILE HAS A VERY LITTLE INFO, IT NEEDS SOME UPDATE.
**Describe the changes needed**
1. Adding of labels of GSSoc
![Screenshot 2024-10-17 144730](https://github.com/user-attachments/assets/d1f8d42a-84bf-4321-9065-5e06e04d97d8)
2. New section about the technology used - PYTHON
3. Adding a section about the contribution points.
![Screenshot 2024-10-18 171025](https://github.com/user-attachments/assets/efd41f06-9cb7-445f-a860-909dff6b1bd4)
4. Adding a GSSoC guidelines file.
5. Adding a ending and Join Us note.

PLEASE ASSIGN ME THIS ISSUE AND ADD THE OFFICIAL LABELS.
Thank you @Kota-Karthik

**Comment by techy4shri** [comment]
@ABHISIKTAcommits, this is a blatant instance of point farming and a violation of our Contributing Guidelines. Consider this your final warning. Any further trivial README issues will result in an immediate ban and further repercussions. Familiarize yourself with the documentation to avoid severe consequences.
