### ISSUE TITLE
[Enhancement] Static site documentation

### ISSUE THREAD

**Issue by yashksaini-coder** [Kota-Karthik/twinTrim#126]
**Describe the enhancement**
Creating a full easy deployable & flexible markdown based documentation site with proper navbar items

**Why is this enhancement necessary?**
Having a proper documentation site for your project keep other in the loop of nay changes and guides for beginners for project setup

**Proposed solution**
Using an external package for creating building & deploying site using gh-pages

**Alternatives considered**
If applicable, mention any alternative solutions you've considered.

**Additional context**
Add any other context or screenshots related to the enhancement here.

**Comment by yashksaini-coder** [comment]
@Kota-Karthik review this issue & assign it to me as gssoc contributor

**Comment by Kota-Karthik** [comment]
@yashksaini-coder 
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder make sure to create a separate branch before making the necessary changes and retain the folder structure.

don't u worry I will follow the guidelines
