### ISSUE TITLE
Enhance Error Handling in File Operations

### ISSUE THREAD

**Issue by protham02** [Kota-Karthik/twinTrim#127]
The current implementation of file operations (such as reading, deleting, or moving files) lacks robust error handling, which can lead to unexpected crashes or uninformative error messages. Enhancing the error handling will improve the user experience by providing clear feedback when something goes wrong, making debugging easier and ensuring that the application behaves more predictably.

**Comment by Swathireddy-22** [comment]
@Kota-Karthik please assign it to me. I want to contribute it

**Comment by protham02** [comment]
@Kota-Karthik Kindly assign it to me.

**Comment by Kota-Karthik** [comment]
@protham02 
make sure to create a separate branch before making the necessary changes and retain the folder structure.
Strictly follow `PR_TEMPLATE` before raising a PR

**Comment by techy4shri** [comment]
@protham02 Please update on discord about your progress.

**Comment by protham02** [comment]
working on it, will send you soon.

**Comment by Kota-Karthik** [comment]
@protham02 any updates?

**Comment by techy4shri** [comment]
Closing this now.
