### ISSUE TITLE
[Doc] : Visual Enhancements , Fostering Contact Channel and enabling Contributors List in README

### ISSUE THREAD

**Issue by Varunshiyam** [Kota-Karthik/twinTrim#129]
**What documentation needs to be updated?**

- To enhance communication and provide direct access to Project Guidance, I plan to include a dedicated Contact section 👤. This section will feature the LinkedIn and GitHub profiles of each mentors and Admin⚡️ enabling contributors to readily connect with them and address any project-related queries. 

- Additionally, to improve readability and organization, I Planned to implement clear visual separations between each section of the contributor documentation, ensuring a user-friendly and easily navigable 🚏 experience. 

- Finally, to foster a welcoming 🙏🏻 and inclusive environment, I will incorporate personalized welcome messages for our Repository.

- To effectively convey the essence of our project and its objectives, I propose creating a customized cover image for the repository.

---

**Additional context**
- Kindly Assign me this Issue Under 🌸Gssoc, ☘️hacktoberfest . I'm  grateful to work with Talented Crews✨

**Comment by techy4shri** [comment]
I recommend reading documentation prior to raising an issue related to it. We are strictly against point farming and this is an invalid issue as pointed in our Contribution Guidelines. This is your first warning, any further violation of our guidelines will result in serious consequences.
Closing this on account of being invalid and a violation of repository guidelines.
