### ISSUE TITLE
Write Unit Tests for `setMaxFileSize` Method

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#13]
- **Description**: Write unit tests for the `setMaxFileSize` method to ensure it sets the maximum file size correctly and handles invalid inputs gracefully.
   - **Resources**: Follow the [pytest getting started guide](https://docs.pytest.org/en/stable/getting-started.html) for writing tests.
   - **Path**: `twinTrim/dataStructures/fileFilter.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

**Comment by kushwxha** [comment]
can you please assign this issue to me??

**Comment by Kota-Karthik** [comment]
@kushwxha 
Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by kushwxha** [comment]
#31 can you review this pr is it ok or i have to make some changes

**Comment by Kota-Karthik** [comment]
@kushwxha
You don’t need to create any folder within tests! I’ve been explaining how to maintain the file structure all along. I’ve left a review on your PR—please address it. Also, don’t close and reopen your PR whenever you make fixes. Just use the necessary git commands to update it.

**Comment by kushwxha** [comment]
@Kota-Karthik 
so for all the pr you have assigned to me i just need to create a file name fileFilter and write the code in it and then do pr

**Comment by Kota-Karthik** [comment]
@kushwxha yesss

**Comment by kushwxha** [comment]
ok

**Comment by kushwxha** [comment]
@Kota-Karthik 
can you check it now? and tell me that i have to do this for other issues also. #31

**Comment by Kota-Karthik** [comment]
@kushwxha 
Do the tests still pass correctly without any failure? 
Provide relevant screenshots in comment 
Then we are good to go!

**Comment by kushwxha** [comment]
yes.
![image](https://github.com/user-attachments/assets/471c7832-786e-407b-822f-a046065ef3f6)
and i have to do same for other issues also??

**Comment by Kota-Karthik** [comment]
@kushwxha 
Yes you have to do same
