### ISSUE TITLE
[Bug]  Application Crashes When Scanning Large Directorie

### ISSUE THREAD

**Issue by Jaswithadabbiru** [Kota-Karthik/twinTrim#131]
Description:
The application crashes unexpectedly when attempting to scan directories that contain a large number of files (specifically over 10,000 files). This issue appears to be related to memory management and may lead to loss of user data or progress.

Steps to Reproduce:

Open the TwinTrim application.
Select a directory that contains more than 10,000 files (e.g., C:\Users\Username\Documents\LargeFolder).
Click on the Scan button.
Monitor the application as it attempts to process the files.

Expected Behavior:
The application should successfully scan the directory and provide a list of duplicate files without crashing.

Here’s a detailed bug report for the issue titled "[Bug] Application Crashes When Scanning Large Directories":

🐞 Bug Report
Title: [Bug] Application Crashes When Scanning Large Directories

Reported By: [Your Name or GitHub Username]

Date: [Date of Report]

Description:
The application crashes unexpectedly when attempting to scan directories that contain a large number of files (specifically over 10,000 files). This issue appears to be related to memory management and may lead to loss of user data or progress.

Steps to Reproduce:

Open the TwinTrim application.
Select a directory that contains more than 10,000 files (e.g., C:\Users\Username\Documents\LargeFolder).
Click on the Scan button.
Monitor the application as it attempts to process the files.

Expected Behavior:
The application should successfully scan the directory and provide a list of duplicate files without crashing.

Actual Behavior:
The application crashes during the scanning process, and no results are returned. A message indicating that the application has stopped working may appear.

Priority: High
This issue significantly impacts usability for users with large directories.

**Comment by Kota-Karthik** [comment]
@Jaswithadabbiru 
I had tested this tool multiple times on a directory with 30000+ files 
could you be more specific ?
can you tell me what is the size of that directory ?
Do you have any screenshots that supports your statement?

**Comment by techy4shri** [comment]
@Jaswithadabbiru  if you do not reply by tonight, I will close this issue.
