### ISSUE TITLE
[Documentation] Add FAQ Section

### ISSUE THREAD

**Issue by Jaswithadabbiru** [Kota-Karthik/twinTrim#132]
What documentation needs to be updated?
The main project documentation, specifically the README file or the dedicated documentation website, requires an update to include a Frequently Asked Questions (FAQ) section.

Describe the changes needed

Create an FAQ Section: Add a new section titled "Frequently Asked Questions" after the installation instructions or usage examples.

Proposed Questions to Include:

What should I do if the application crashes while scanning?
Provide troubleshooting steps, such as checking for large directories or updating the application.
How does TwinTrim identify duplicate files?
Explain the methodology (e.g., comparing file names, sizes, and potentially content).
Can I exclude certain files or directories from the scan?
Describe how to use the exclusion feature effectively.
What should I do if I accidentally delete the wrong files?
Offer guidance on restoring deleted files, if applicable.
Is there a limit to the number of files I can scan?
Address any known limitations regarding file counts or sizes.
How can I report a bug or request a feature?
Include instructions on how to contribute feedback or issues via GitHub.
Format and Style: Ensure that the FAQ section maintains consistent formatting with the rest of the documentation, using bullet points or numbered lists for clarity.

Additional context
Adding an FAQ section will improve user experience by providing quick answers to common concerns, reducing the volume of support requests. This enhancement will also demonstrate the project's commitment to user-friendly documentation. By anticipating user questions, we can foster a more knowledgeable user base and help them utilize TwinTrim more effectively.

**Comment by techy4shri** [comment]
@Jaswithadabbiru  you are hereby banned from this repository; no contribution from you will be accepted unless approved by @Kota-Karthik , the PA of this repository on discord. This is the third spam issue I have seen from you here which is just another attempt at point farming. You will be reported in GSSoC-ext if I see any more rule violation.
