### ISSUE TITLE
[Feature] Integrate Cloud Storage Support

### ISSUE THREAD

**Issue by Jaswithadabbiru** [Kota-Karthik/twinTrim#134]
Is your feature request related to a problem? Please describe.
Currently, TwinTrim only scans local directories for duplicate files, which limits its usability for users who primarily store their files in cloud storage services like Google Drive, Dropbox, or OneDrive. As more users migrate to cloud-based storage solutions, the lack of cloud integration hinders the application's relevance and effectiveness for a significant portion of potential users. This gap in functionality means that users have to manually download files from the cloud to their local systems to check for duplicates, which is time-consuming and inefficient.

Describe the solution you'd like
I would like to see an integration that allows TwinTrim to directly access and scan files stored in popular cloud storage services. This feature should enable users to:

Authenticate their cloud storage accounts through OAuth or API keys.
Browse and select specific folders or entire accounts for duplicate scanning.
View results and manage duplicates within the cloud storage interface, similar to how local files are managed.
Describe alternatives you've considered

Manual Downloading: Users can manually download files from cloud storage to their local machines for scanning. However, this method is cumbersome and defeats the purpose of having cloud storage.

Standalone Cloud Storage Apps: Some applications already offer duplicate detection for cloud storage, but they lack the comprehensive features and user experience that TwinTrim provides for local files. Developing our solution could set TwinTrim apart in the market.

Additional context
Integrating cloud storage support will significantly enhance the functionality of TwinTrim and expand its user base. This feature can be marketed as a major improvement, appealing to users who utilize cloud storage solutions. Additionally, this integration may require a review of the project’s security protocols to ensure user data is handled safely and comply with cloud service API usage policies.

**Comment by techy4shri** [comment]
SPAM
