### ISSUE TITLE
[Workflow] Improve Contribution Guidelines for Pull Requests

### ISSUE THREAD

**Issue by Jaswithadabbiru** [Kota-Karthik/twinTrim#136]
What workflow needs to be updated?
The current contribution workflow for submitting pull requests lacks clarity and detail, which can lead to confusion among contributors. Specifically, the guidelines do not provide sufficient information on code formatting, testing requirements, and the review process.

Describe the proposed changes

Update Contribution Guidelines: Revise the CONTRIBUTING.md file to include:

Code Formatting: Specify the code style guide (e.g., PEP 8 for Python) and any tools to enforce it (like black or prettier).
Testing Requirements: Clearly outline the expectation for writing unit tests for any new features or bug fixes. Include instructions on how to run existing tests before submitting a pull request.
Pull Request Template: Introduce a pull request template that requires contributors to fill out sections about the changes made, related issues, and testing done.
Review Process: Detail the expected timeline for reviews and any labels that contributors should use to categorize their pull requests (e.g., bug, enhancement, feature).
Add a CI/CD Pipeline: Set up a Continuous Integration/Continuous Deployment (CI/CD) pipeline to automatically run tests on all pull requests. This will ensure that any new code meets the project’s quality standards before being merged.

Motivation
Improving the contribution workflow is necessary to streamline the process for contributors and maintain code quality. Clear guidelines will help reduce misunderstandings, ensure consistency across contributions, and encourage more developers to participate in the project. Additionally, implementing a CI/CD pipeline will help catch errors early, making the review process smoother and more efficient.

Additional context
By enhancing the contribution guidelines and integrating CI/CD practices, we can foster a more collaborative and productive environment for contributors. This change is particularly important as the project grows and more developers begin contributing. Better workflows will ultimately lead to higher-quality code and a more robust application.

**Comment by nigam-divyanshi-dev** [comment]
please assign this issue to me under gssoc or hacktoberfest so that i can contribute . thankyou .

**Comment by techy4shri** [comment]
And this turned from a workflow issue to another doc issue. This is your first warning @Jaswithadabbiru , we are strictly against point farming. Closing this issue on account of being invalid.
