### ISSUE TITLE
[Documentation] Our Contributors  Section

### ISSUE THREAD

**Issue by siri-chandana-macha** [Kota-Karthik/twinTrim#137]
I would like to add an **"Our Contributions"** section in the README to highlight the collaborative efforts and individual contributions of team members. This addition will foster a sense of ownership and encourage further engagement, showcasing the value each person brings to the project.

@Kota-Karthik
Kindly assign this issue under gssoc-extd, hacktoberfest , hacktoberfest-accepted and level1

**Comment by Kota-Karthik** [comment]
@siri-chandana-macha 
Thank you very much 
But honestly we don't need this section right now!
