### ISSUE TITLE
[Documentation] Add our valuable contributors to README.md

### ISSUE THREAD

**Issue by Anjalis14** [Kota-Karthik/twinTrim#138]
demo like this 
![455](https://github.com/user-attachments/assets/b74e9cb0-99c6-4501-935d-4a3b93517996)

**Comment by nigam-divyanshi-dev** [comment]
please assign this issue to me under gssoc or hacktoberfest so that i can contribute . thankyou .

**Comment by techy4shri** [comment]
This is your frist warning @Anjalis14 , read the Contribution guidelines first befo raising issues. Closing this on account of being invalid.
