### ISSUE TITLE
Write Unit Tests for `setFileType` Method

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#14]
- **Description**: Write unit tests for the `setFileType` method to verify it sets the file type regex correctly. Test with various valid and invalid file types.
   - **Resources**: Use the [pytest getting started guide](https://docs.pytest.org/en/stable/getting-started.html) for writing tests.
   - **Path**: `twinTrim/dataStructures/fileFilter.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

**Comment by kushwxha** [comment]
can you asign it to me?

**Comment by Kota-Karthik** [comment]
@kushwxha Yes, 
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by kushwxha** [comment]
#26 added the unit test for setfiletype method

**Comment by Kota-Karthik** [comment]
@kushwxha 
please check the review I left

**Comment by kushwxha** [comment]
hey, in test folder only I have to create the unit test files.

**Comment by Kota-Karthik** [comment]
@kushwxha 
as this issue belongs to a method within fileFilter file
create a file named fileFilter within tests folder 
then write the tests that belong to that particular file
do same for other issues

**Comment by kushwxha** [comment]
hey now you can check i made a new folder and added the unit test in it

**Comment by kushwxha** [comment]
#30 this is the new pull request

**Comment by Kota-Karthik** [comment]
@kushwxha 
It's great but you really need to understand folder structure of the project 
Just creat a single file in tests folder, named  fileFilter
then write the tests that belong to that particular file
do same for other issues
If you have doubts feel free to ask 
Then proceed with PR

**Comment by kushwxha** [comment]
i have was trying to create only fileFilter folder but when i am running test in terminal its giving me error that there is module named twinTrim so for that i had to add conftest.py so that the unit test can use the module.

can you give the review in pr

**Comment by Kota-Karthik** [comment]
@kushwxha 
You don’t need to create any folder within tests! I’ve been explaining how to maintain the file structure all along. I’ve left a review on your PR—please address it. Also, don’t close and reopen your PR whenever you make fixes. Just use the necessary git commands to update it.

**Comment by kushwxha** [comment]
hey @Kota-Karthik ,
i have made changes in this #30 pr also can please check it.
i have attached the screenshot for  
![image](https://github.com/user-attachments/assets/08766cbb-050b-405c-97d9-51a80b3881da)

**Comment by kushwxha** [comment]
hey @Kota-Karthik,
i am getting conflict when i am trying  pr for this issue.
![image](https://github.com/user-attachments/assets/9951f470-21de-4bbf-be0b-31015f6f4b45)

**Comment by Kota-Karthik** [comment]
@kushwxha 
just try to resolve the conflicts!
then it would all be done !

**Comment by kushwxha** [comment]
hey @Kota-Karthik, 
i have resolved the conflict, can you check it now??
and please don't forget to add labels to pr.
