### ISSUE TITLE
Duplicate File Report Generation

### ISSUE THREAD

**Issue by sv410** [Kota-Karthik/twinTrim#140]
Feature Request: Duplicate File Report Generation
Is your feature request related to a problem? Please describe. Managing duplicate files can be cumbersome, and users often find it difficult to track and review duplicates detected by TwinTrim. A detailed report of duplicates is essential for efficient management and decision-making.

Describe the solution you'd like Implement a feature to generate detailed reports of duplicate files. These reports should include file paths, sizes, and modification dates, and be exportable in formats such as CSV and PDF. Additionally, users should be able to schedule periodic report generation for ongoing monitoring.

Describe alternatives you've considered

Manual Review: Allow users to manually review duplicate files through the command line interface. However, this approach can be time-consuming and less efficient for users with large numbers of files.

Basic Logging: Create simple log files for duplicate detection events. While useful, log files lack the detailed and structured format that reports provide.

Additional context This feature will greatly enhance user experience by providing clear and structured insights into duplicate files. It will also help in the organization and management of large file systems. Below is a conceptual mockup of the feature:

Report Format Selection: Users can select their preferred export format (CSV, PDF).

Report Customization: Options to include specific data points in the report.

**Comment by Wahid7852** [comment]
1. Not a debug application for us to generate log files for the user.
2. There are automated and manual modes for the application to perform for a reason
