### ISSUE TITLE
[Feature] file preview before deletion

### ISSUE THREAD

**Issue by sv410** [Kota-Karthik/twinTrim#143]
File Preview Before Deletion

Problem: Users often find it challenging to decide which duplicates to delete without knowing what the files contain. Accidentally deleting important files due to lack of information can be frustrating.

Solution: Implement a feature that allows users to preview the contents of duplicate files before confirming their deletion. This can be achieved by:

Adding a file type detection mechanism to identify previewable files (e.g., images, PDFs).

Providing a preview option in the command-line interface to display the content of the selected duplicate files.

Alternatives Considered:

Manual File Verification: Users manually check file contents in their file system, which is time-consuming and inefficient.

Detailed File Information Display: Show detailed metadata (size, creation date, etc.) instead of a full preview, but this might not provide enough context to make an informed decision.

Additional Context: Implementing file previews enhances user confidence in the tool, ensuring important files are not accidentally deleted. This feature can be particularly useful in media-heavy directories where visual confirmation is essential.

**Comment by P4R1H** [comment]
Would like to be assigned to this 🙏

**Comment by techy4shri** [comment]
@Kota-Karthik I don't think this is necessary but please have a look.

**Comment by Kota-Karthik** [comment]
@sv410 
All files won't be deleted, only duplicates will be deleted and  original file would be intact
@techy4shri even I think that it's not necessary 
Close it!
