### ISSUE TITLE
[Documentation] Enhancement Of Contributing Guidelines.md

### ISSUE THREAD

**Issue by milansamuel609** [Kota-Karthik/twinTrim#144]
**What documentation needs to be updated?**
The contributing.md file is not in a structured manner. Also some sections are missing. I can enhance it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute.

**Describe the changes needed**

Wanted to do the following changes :-

1) Enhance the project structure
2) Add need help with the basics section
3) Add project structure section
4) Add additional method of contributing through GitHub desktop section
5) Add good coding practices section
6) Add the help and support section
7) Add the pull request section
8) Add issue report process section

**Additional context**
Add any other context about the documentation request here.

**Comment by techy4shri** [comment]
Mention ONE section which is not structured. Let's see what you have.

**Comment by techy4shri** [comment]
I see this is a case of copy pasting issues across multiple repos, you are hereby banned from this repo till the end of the current programs.
