### ISSUE TITLE
[Feature] Creating frontend using Stremlit in python

### ISSUE THREAD

**Issue by KGupta2601** [Kota-Karthik/twinTrim#147]
Integrate a frontend for TwinTrim using Streamlit and authenticate with streamlit, a Python library for creating interactive web applications. This frontend should allow users to perform key actions like selecting directories to scan, viewing duplicate files in an organized manner, and confirming or adjusting auto-removal settings.

**Comment by KGupta2601** [comment]
@Kota-Karthik kindly assign me this issue along with the labels of gssoc extended,hacktoberfest and level

**Comment by Kota-Karthik** [comment]
@KGupta2601 
Thanks for raising this issue 
But as our prject is a CLI tool 
I don't really think this issue will be of any use to us 
But we encourage you to raise other issues
