### ISSUE TITLE
Write Unit Tests for `addFileExclude` Method

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#15]
- **Description**: Write unit tests for the `addFileExclude` method to ensure it adds file names to the exclusion list correctly and prevents duplicates.
   - **Resources**: Refer to the [pytest getting started guide](https://docs.pytest.org/en/stable/getting-started.html) for setting up tests.
   - **Path**: `twinTrim/dataStructures/fileFilter.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

**Comment by SandyK1002** [comment]
Hi, can I please get assigned to this issue.

**Comment by Kota-Karthik** [comment]
@SandyK1002 Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by Bhavya445** [comment]
can u plss assign this to me

**Comment by Kota-Karthik** [comment]
@SandyK1002 
are you still working on this?

**Comment by SandyK1002** [comment]
Yes, I'm almost done. Just give me a day more

**Comment by techy4shri** [comment]
@SandyK1002 kindly reply by tonight or your assigned issues will be assigned to someone else.

**Comment by Kota-Karthik** [comment]
@SandyK1002 I am unassigning you and assigning this issue to @Bhavya445 
@Bhavya445
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by Bhavya445** [comment]
thank you sir

**Comment by JahnaviDhanaSri** [comment]
Hello can you please assign this issue to me

**Comment by techy4shri** [comment]
@JahnaviDhanaSri PLease raise your own issues instead of commenting on already assigned ones.

**Comment by Kota-Karthik** [comment]
@Bhavya445 
any updates ?
are you even working on this ?
reply by EOD , else i will be unassigning you !

**Comment by techy4shri** [comment]
Whoever replies first to my comment will be assigned. @Bhavya445 you are unassigned due to inactivity.

**Comment by ShirshenduR** [comment]
asaign me

**Comment by Kaos599** [comment]
@Kota-Karthik @techy4shri can i work on this please?

**Comment by Kota-Karthik** [comment]
@ShirshenduR you can work on this!
