### ISSUE TITLE
[Documentation] add gssoc fest logo GitHub repo stats in the readme Complete this process in GitHub using markdown !!

### ISSUE THREAD

**Issue by REHAN-18** [Kota-Karthik/twinTrim#150]
**What documentation needs to be updated?**
 add gssoc fest logo GitHub repo stats in the readme Complete this process in GitHub using markdown !!
**Describe the changes needed**
It will help the contributor to understand the process go GitHub 
like this I will make 
<img width="834" alt="Screenshot 2024-10-26 at 11 48 23 PM" src="https://github.com/user-attachments/assets/ea1da93f-520b-4713-9e20-4826d7d7521a">
<img width="809" alt="Screenshot 2024-10-26 at 11 50 42 PM" src="https://github.com/user-attachments/assets/9a38c256-5f0a-4b8e-95a2-4ba89c1041f8">
<img width="926" alt="Screenshot 2024-10-26 at 11 50 45 PM" src="https://github.com/user-attachments/assets/b0365191-0428-440c-903d-b69831a232b5">

**Additional context**
Add any other context about the documentation request here.

**Comment by REHAN-18** [comment]
@Kota-Karthik pls assign me !!

**Comment by techy4shri** [comment]
Closing this on account of contribution guidelines violation. Read the docs @REHAN-18 otherwise you will face consequences.
