### ISSUE TITLE
Implement Directory Comparison Mode

### ISSUE THREAD

**Issue by imDarshanGK** [Kota-Karthik/twinTrim#151]
Motivation: Adding a directory comparison mode will make it easier for users to identify duplicates across multiple directories, find unique files, and manage their file system more efficiently. It will be especially useful for syncing content and cleaning up redundant files across backup directories.

**Comment by Kota-Karthik** [comment]
@imDarshanGK 
can you be more specific?
what exact changes you want to make ?
your issue title is clear but your issue description puts me in dilemmaa

**Comment by imDarshanGK** [comment]
Hi @Kota-Karthik,

Thank you for your prompt reply! Let me clarify the changes I'd like to propose for the Directory Comparison Mode feature:

Specific Changes:

1}File Comparison Across Directories:
Add an option --compare to enable comparison between two or more directories.

2} Sync Unique Files:

Implement an option --sync to allow users to synchronize unique files from one directory to another.

3)Report Generation:

Introduce a --report option to generate a summary of the comparison.
The report can be output in CSV or TXT format, detailing unique and duplicate files.

I hope this gives a clearer picture of the intended changes. Let me know if you need further details or have any questions!

Best regards,
@imDarshanGK

**Comment by techy4shri** [comment]
twinTrim is a CLI based python package built to simplify finding the duplicates and delete it easily. We focus on simplicity so while directory comparision could be implemented in a way, I am not sure if this is what we want. @Kota-Karthik thoughts?

**Comment by Wahid7852** [comment]
The File Comparison makes no sense since the tool already has manual and automatic mode.
the sync option makes no sense since we are here to only delete files. Syncing is not planned.
Report Generation is something which already happens.

I will be waiting for @Kota-Karthik thoughts before closing

**Comment by Kota-Karthik** [comment]
@imDarshanGK 
We are not interested with the issue
Thank you very much for contributing!
