### ISSUE TITLE
Updates.py

### ISSUE THREAD

**Issue by Khushi-Dua** [Kota-Karthik/twinTrim#169]
**Describe the test request**
This request aims to improve the existing tests for the AllFileMetadata class, specifically focusing on:

Ensuring compatibility with Path objects to streamline path handling.
Enhancing error handling checks for non-existent files to verify that -1 is returned when expected.
Improving readability in assert statements for more informative test outputs.

**Motivation**
These changes are essential to ensure that the tests are robust, readable, and follow best practices for handling file paths. Enhancing error handling and making assertions clearer will provide better test diagnostics and reduce the chance of misinterpretation when tests fail.

**Steps to Reproduce**
To observe the improvements, run the updated tests. The key changes include:

Returning Path directly in temp_file to improve compatibility and code clarity.
Enhanced assert messages, making test failures easier to understand at a glance.

**Additional context**
This update follows Python’s best practices with pathlib for file handling and is part of a larger initiative to make tests more reliable and readable across the codebase.

**Comment by Wahid7852** [comment]
Have you checked if what youre suggesting, is broken or doesnt exist in the project?

**Comment by techy4shri** [comment]
@Khushi-Dua you have 24 hours to reply to this otherwise I will be closing this issue.

**Comment by Khushi-Dua** [comment]
By "ensuring compatibility with Path objects to streamline path handling," I mean using pathlib.Path objects directly in the code, instead of converting them to strings.

In the original code, the temp_file fixture converted the Path object to a string before returning it. However, if we keep it as a Path object, the code becomes cleaner and avoids unnecessary conversions, making it easier to work with file paths in subsequent operations. This approach also aligns with modern Python best practices, where pathlib is preferred over string-based path manipulation for its clarity and flexibility.

**Comment by techy4shri** [comment]
@Kota-Karthik take a look please. 
@Khushi-Dua I need more info from you and you will need to update us on discord for further communication regarding this if Karthik assigns you.

**Comment by Khushi-Dua** [comment]
U hve not updated?

**Comment by Kota-Karthik** [comment]
@techy4shri 
I dont think this is necessary rn 
I am closing this issue 
@Khushi-Dua Thanks for your efforts
