### ISSUE TITLE
Write Unit Tests for `handle_and_remove` Function

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#17]
- **Description**: Write unit tests to validate the behavior of the `handle_and_remove` function. Test cases should cover:
     - Successfully deleting a file.
     - Handling a `FileNotFoundError`.
     - Handling a `PermissionError`.
     - Handling other exceptions.
   - **Resources**: Refer to the [pytest getting started guide](https://docs.pytest.org/en/stable/getting-started.html) for writing tests.
   - **Path**: `twinTrim/utils.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

**Comment by kushwxha** [comment]
can you assign it to me??

**Comment by Kota-Karthik** [comment]
@kushwxha 
You are already assigned to a lot of issues 
Try to finish them off , they I will assign you this one!

**Comment by Varun-malviya5** [comment]
hi @kushwxha please assign me this issue

**Comment by Varun-malviya5** [comment]
hii @Kota-Karthik please assign me this

**Comment by Kota-Karthik** [comment]
@Varun-malviya5 Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by kushwxha** [comment]
hey @Kota-Karthik , 
can you please assign it to me?

**Comment by seemab24** [comment]
Hi @Kota-Karthik can you assign this issue to me ?

**Comment by kushwxha** [comment]
hey, can you assign it to me??
