### ISSUE TITLE
Code Refactoring and Error Handling Improvements

### ISSUE THREAD

**Issue by Sharmeen20** [Kota-Karthik/twinTrim#170]
**Is your feature request related to a problem? Please describe.**
I have noticed that the current file handling script lacks comprehensive error tracking and logging, making it difficult to diagnose issues during file processing. Additionally, the color management for console outputs is hard-coded and not standardized, which can lead to inconsistencies and decreased readability in the code.

**Describe the solution you'd like**
I propose implementing a logging mechanism to capture errors and important events throughout the file processing workflow. This would help in diagnosing issues more effectively. Additionally, creating a centralized color management system (e.g., a Colors class) would standardize the color usage across the application, improving code readability and maintainability.

**Describe alternatives you've considered**
Manual Print Statements: Adding print statements for error handling, but this would clutter the code and make it harder to manage.
Using External Libraries: Considering external libraries for logging, but they might introduce unnecessary complexity when Python’s built-in logging module suffices.
Retaining Current Structure: Keeping the current error handling and color usage as is, which would not address the existing problems.

**Additional context**
Implementing these changes would not only enhance the maintainability of the code but also improve the user experience by providing clearer feedback during file processing. Here are a couple of screenshots showing current output and potential improvements with logging and standardized colors.

**Comment by techy4shri** [comment]
I see no screenshot provided. We are limiting the usage of external libraries as that creates another issue.
Explain what the logging will help with?

**Comment by techy4shri** [comment]
@Sharmeen20 you need to reply by EOD or I will be closing this issue.
