### ISSUE TITLE
 Write Unit Tests for `parse_size` Function

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#19]
- **Description**: Write unit tests for the `parse_size` function to ensure it correctly converts size strings to bytes, covering cases like:
     - Inputs like "10kb", "1mb", "1.5gb".
     - Handling invalid formats and ensuring they return 0 or raise an exception as needed.
   - **Resources**: Refer to the [pytest getting started guide](https://docs.pytest.org/en/stable/getting-started.html) for writing tests.
   - **Path**: `twinTrim/utils.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

**Comment by Kota-Karthik** [comment]
@smartfellow1234 
Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by SaanyaGarg5** [comment]
i can solve this issue ..
assign that task to me

**Comment by Kota-Karthik** [comment]
@SaanyaGarg5 
It's already assigned to @smartfellow1234 
If he doesn't complete it by tomorrow then I will assign it to you!
