### ISSUE TITLE
Write Unit Tests for `compare_and_replace` Method

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#2]
- **Description**: Write tests for the `compare_and_replace` method to ensure:
     - The correct file is removed based on the modification time.
     - No file is removed if one or both files don't exist.
   - **Resources**: Refer to the [pytest guide](https://docs.pytest.org/en/stable/getting-started.html) for test setup.
   - **Path**: `twinTrim/dataStructures/allFileMetadata.py`
   - **Code to be added**: `tests`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests.

**Comment by SaanyaGarg5** [comment]
you can assign that task to me..

**Comment by KartikSaxena19** [comment]
you can assign task to me

**Comment by tarunkumar2005** [comment]
I would like to contribute to this. @Kota-Karthik Assign this to me under gssoc-ext and hacktoberfest

**Comment by Kota-Karthik** [comment]
@SaanyaGarg5 
Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by SaanyaGarg5** [comment]
Ok

**Comment by techy4shri** [comment]
@SaanyaGarg5 you have 2 more days to work on this before this issue is opened for claim again.

**Comment by KartikSaxena19** [comment]
Assign this task to me i want to work with you

**Comment by KartikSaxena19** [comment]
if this issue is not resolved you can assign this to me

**Comment by JahnaviDhanaSri** [comment]
Hi @Kota-Karthik,

I would like to take on the task of writing unit tests for the compare_and_replace method as outlined in issue #2. Ensuring the reliability of this method through proper testing is essential, and I’m excited to contribute!
Here’s my proposed plan:
Test Cases:
Verify that the correct file is removed based on the modification time.
Confirm that no file is removed if one or both files do not exist.
Test Framework: I will use pytest for setting up and executing the tests, following the guidelines provided in the pytest documentation.

File Structure: I will ensure that the tests are organized in a manner consistent with the existing file structure, keeping the organization clear and maintainable.

Could you please assign this issue to me

**Comment by Sai-ganesh-0004** [comment]
Hello I would like to work on this Can you assign it to me

**Comment by techy4shri** [comment]
@KartikSaxena19 and @tarunkumar2005 would either of you like to work on this issue?

**Comment by tarunkumar2005** [comment]
@techy4shri I can work on this

**Comment by KartikSaxena19** [comment]
No can't work on this issue immediately as I'm preparing for my internal exams

**Comment by techy4shri** [comment]
@tarunkumar2005 you are assigned. @KartikSaxena19 all the best for your exams!
