### ISSUE TITLE
 Optimize `get_file_hash` Function for Large Files

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#20]
- **Description**: Investigate the `get_file_hash` function to optimize it for very large files by possibly increasing the buffer size or using a more efficient hashing algorithm if necessary.
   - **Resources**: Refer to the [Python hashlib documentation](https://docs.python.org/3/library/hashlib.html) for more information on hashing algorithms.
   - **Path**: `twinTrim/utils.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

**Comment by ShirshenduR** [comment]
can I try to solve the issue

**Comment by ShirshenduR** [comment]
[] #34

**Comment by Kota-Karthik** [comment]
@ShirshenduR ,
Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by ShirshenduR** [comment]
Okay sir

**Comment by ShirshenduR** [comment]
#34
