### ISSUE TITLE
Write Unit Tests for `handleAllFlag` Function

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#21]
- **Description**: Write unit tests for the `handleAllFlag` function to verify its functionality. Test cases should include:
     - Handling of a directory with no files.
     - Handling of files filtered by `file_filter`.
     - Successful execution of the function and completion of all tasks.
   - **Resources**: Use the [pytest getting started guide](https://docs.pytest.org/en/stable/getting-started.html) for writing tests.
   - **Path**: `twinTrim/flagController.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

**Comment by Prakhar29Sharma** [comment]
I would like to work on this issue, please assign it to me

**Comment by Kota-Karthik** [comment]
@Prakhar29Sharma , yes, make sure to create a separate branch before making the necessary changes and retain the folder structure. Create a file named `flagController.py` in the `tests` folder and write the necessary tests in it. When creating a PR, mention 'Fixes <issue number>' and include screenshots so I can verify that the tests run without any failures.

**Comment by kushwxha** [comment]
hey, can you assign it to me??

**Comment by Prakhar29Sharma** [comment]
> hey, can you assign it to me??

Hey @kushwxha, I'm already working on it.
