### ISSUE TITLE
Write Unit Tests for `find_duplicates` Function

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#22]
- **Description**: Write unit tests for the `find_duplicates` function to ensure it behaves as expected. Test cases should cover:
     - Finding duplicates in a directory with multiple files.
     - Handling of directories with no files.
     - Proper filtering of files using `file_filter`.
   - **Resources**: Refer to the [pytest getting started guide](https://docs.pytest.org/en/stable/getting-started.html) for writing tests.
   - **Path**: `twinTrim/flagController.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

**Comment by valnayy** [comment]
Can you assign that issue to me ?

**Comment by Kota-Karthik** [comment]
@valnayy 
Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by Shukla000** [comment]
Please assign me this task

**Comment by Kota-Karthik** [comment]
@Shukla000 
currently someone else is working on this issue 
You can check out our other open issues or create issues and get them assigned!

**Comment by Kota-Karthik** [comment]
@valnayy 
Are you still working on this?

**Comment by techy4shri** [comment]
@valnayy you are being unassigned. @Shukla000 you can work on this issue.

**Comment by kushwxha** [comment]
hey @Kota-Karthik,
can you assign it to me??

**Comment by techy4shri** [comment]
@kushwxha @Shukla000 is already assigned. Please go look for an issue which has not been assigned or raise your own.

**Comment by JahnaviDhanaSri** [comment]
Hello can you please assign this issue to me

**Comment by techy4shri** [comment]
@Shukla000 Kindly confirm once whether you are working on this or not.
@JahnaviDhanaSri We follow a first come, first serve policy, so unless the people who commented before you cannot work on this, you won't be assigned.

**Comment by Sai-ganesh-0004** [comment]
Hello I would like to work on this Can you assign it to me

**Comment by techy4shri** [comment]
This is third time I see you commenting on an already assigned issue @Sai-ganesh-0004 
Now let me make two things clear here.

1. This repository follows the FCFS policy so issues are assigned accordingly.
2. Continious spam commenting on already assigned issues can result in serious consequences included but not limited to a warning or ban from the repository along with disciplinary actions.
3. We do not allow points farming here so, proceed with caution or you'll be liable for any and all consequences.

**Comment by tannuiscoding** [comment]
hey, @Kota-Karthik I want to write test cases for this function. Assign me this issue under gssocext and hacktoberfest. 
Here is my approach to write these test cases,
- first, I will define a class `TestFileDuplicates`. (I can do without classes too, it is for better management and easier access).
- in that class I will define these functions using unittests and pyTest.

```python
def create_test_file(path, content):
      pass
def create_test_file(path, content):
     pass
def run_around_tests():
     pass
def test_find_duplicates_same_content(run_around_tests):
     pass
def test_find_no_duplicates(run_around_tests):
     pass
def test_multiple_duplicates(run_around_tests):
     pass
```
- I will test basic functionality and edge cases using unittests

let me know if you have any changes in your mind for this approach.

what libraries I will use:

```python
import unittest
import os
import tempfile
import shutil
from unittest.mock import Mock, patch
import time
import click
import pytest
```

**Comment by techy4shri** [comment]
@Shukla000 you are being unassigned sue to inactivity. @tannuiscoding you are assigned, please try to go for the most optimal approach and in case of doubts, you can discuss on discord. I will assign one task at a time. 
You have 1 week to complete this task.

**Comment by techy4shri** [comment]
This issue is now open to all. Whoever replies to me first ill be assigned.

**Comment by Sai-ganesh-0004** [comment]
I have completed the Issue #4 , So can I give this a try

**Comment by techy4shri** [comment]
@Sai-ganesh-0004 Sure! Go ahead!

**Comment by Hafsa-shoaib989** [comment]
@techy4shri can you please assign this task to me ?

**Comment by techy4shri** [comment]
@Hafsa-shoaib989 do not comment to be assigned on already assigned issue, read the documentation. This is your first warning.

**Comment by Wahid7852** [comment]
@Sai-ganesh-0004 updates

**Comment by Sai-ganesh-0004** [comment]
going to raise pr today

**Comment by techy4shri** [comment]
Good, make sure you have followed the steps detailed in readme for set up to ensure all tests pass and follow the template!
