### ISSUE TITLE
Improve Progress Bar Customization

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#23]
- **Description**: Refactor the progress bar format to allow customization through parameters, rather than hardcoding ANSI escape codes. You can redesign the progress bar to show different stages of scanning and hashing with different colors. Ensure the functionality remains intact.
   - **Resources**: Check the [tqdm documentation](https://tqdm.github.io/) for information on customizing the progress bar.
   - **Path**: `twinTrim/flagController.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

**Comment by In-Saiyan** [comment]
Hello sir, can you assign me #23 please

**Comment by Kota-Karthik** [comment]
@In-Saiyan ,Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by In-Saiyan** [comment]
@Kota-Karthik I am removing this PR and sending a new one. I also added --bar-color and --label-color for customisation.
