### ISSUE TITLE
Replace Inconsistent Color Palette with an Optimal Color Palette for CLI Outputs

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#24]
**Description:**  
The current color palette used in the CLI outputs is inconsistent, making it difficult for users to differentiate between various types of messages (e.g., informational, warning, success). An optimal color palette should be implemented to enhance the readability and user experience of the CLI. The new palette should provide clear visual distinctions for different message types and maintain accessibility standards.

**Resources:**  
- [Beaupy Documentation](https://beaupy.readthedocs.io/en/latest/) for color usage in CLI applications.  
- Best practices for color choices in user interfaces to ensure accessibility and usability.  
- Color contrast checker tools for ensuring optimal readability.

**Path:**  
`twinTrim/flags.py`

**Note:**  
Ensure to maintain the file structure as per the existing files and tests.

**Comment by mienpham04** [comment]
can you assign that to me?

**Comment by Kota-Karthik** [comment]
@mienpham04 
Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by Kota-Karthik** [comment]
@mienpham04 
Are you even working on this?

**Comment by anushka4124** [comment]
@Kota-Karthik 
I noticed the issue regarding the inconsistent color palette in the CLI outputs. I’d like to take on the task of improving the color palette to enhance readability and user experience. I have some ideas for a new palette that adheres to accessibility standards.

Could you please assign this task to me?

**Comment by Kota-Karthik** [comment]
@anushka4124 
This issue is already assigned to someone else 
If she doesn't complete it , I will assign it to you
You can check out our other open issues
@mienpham04 try to complete the issue and make a PR

**Comment by techy4shri** [comment]
This issue is now open to all. Whoever comments first will be assigned.

**Comment by RhiyaBhat** [comment]
@Kota-Karthik 
 I would like to take on the task of improving the color palette to enhance readability and user experience.
Please assign this task to me

**Comment by techy4shri** [comment]
@RhiyaBhat explai your approach.

**Comment by RhiyaBhat** [comment]
I would implement this task by using:
import beaupy
from beaupy.ansi import fg, bg, style, reset

And then assigning a consistent color palette for the various types of messages

**Comment by 2004san** [comment]
I want to work on it, Can you assign it to me? @Kota-Karthik

**Comment by Kota-Karthik** [comment]
@RhiyaBhat 
You can work on this issue 
Before starting to make changes please go through `CONTRIBUTING.MD`
make sure to create a separate branch before making the necessary changes and retain the folder structure, 
strictly follow PR template before raising a PR

**Comment by RhiyaBhat** [comment]
Thank you

**Comment by Kota-Karthik** [comment]
@RhiyaBhat 
reply by EOD 
else I will be unassigning you !

**Comment by RhiyaBhat** [comment]
I will put a pull request soon. Please give me time till tomorrow morning.

**Comment by techy4shri** [comment]
Ok sure but please do make a PR by tomorrow.
