### ISSUE TITLE
 Write Tests for `add_or_update_file` Function

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#4]
- **Description**: Write unit tests to verify that the `add_or_update_file` function:
     - Adds a new file's metadata correctly.
     - Updates metadata when a file with the same hash already exists in the store.
   - **Resources**: Follow the [pytest guide](https://docs.pytest.org/en/stable/getting-started.html) to set up tests.
   - **Path**: `twinTrim/dataStructures/allFileMetadata.py`
   - **Code to be added**: `tests`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests.

**Comment by parshvi1508** [comment]
I am Parshvi Jain.
I am interested in working on this issue under hacktoberfest and GSSOC extended.
Kindly consider assigning this issue to me. I am ready to start and will provide regular updates.

**Comment by Kota-Karthik** [comment]
@parshvi1508 Yes, 
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by parshvi1508** [comment]
@Kota-Karthik I have done doubts regarding it. 
Is it possible to solve them over discord?

**Comment by parshvi1508** [comment]
> @parshvi1508 are you working on this?

@techy4shri Yes, I am working on this.
Sorry for delaying it  but I was facing some issue which has been resolved now.

**Comment by JahnaviDhanaSri** [comment]
Hi @Kota-Karthik,

I would like to take on the task of writing unit tests for the add_or_update_file function as outlined in issue #4. Testing this function is essential to ensure its reliability in managing file metadata accurately.

Here’s how I plan to approach the task:

New File Metadata: I will write tests to verify that when a new file is added, its metadata is correctly stored in the system.

Updating Existing Metadata: I will create scenarios to test that if a file with the same hash already exists, its metadata gets updated appropriately without duplicating entries.

Test Framework: I will follow the pytest guidelines to ensure proper setup and organization of the tests.

File Structure: I will maintain the existing file structure for clarity and consistency in the project.

Could you please assign this issue to me

**Comment by Sai-ganesh-0004** [comment]
Hello I would like to work on this Can you assign it to me

**Comment by techy4shri** [comment]
@parshvi1508 please reply on discord or update here otherwise I will be opening this issue for grabs again.

**Comment by parshvi1508** [comment]
> @parshvi1508 please reply on discord or update here otherwise I will be opening this issue for grabs again.

Had been continuously updating @Kota-Karthik on discord.
The code is ready.
Will just create a PR by tomorrow morning.

**Comment by techy4shri** [comment]
@parshvi1508 ok, please update anything realted to project in project discussions so that I can track updates.

**Comment by Kota-Karthik** [comment]
@parshvi1508 any updates?

**Comment by parshvi1508** [comment]
> @parshvi1508 any updates?
> 

Will raise the PR by 10pm today.

**Comment by parshvi1508** [comment]
I am still facing assertion error with the function code for test_update_existing_file_metadata().
Sorry for the inconvenience.

**Comment by techy4shri** [comment]
@parshvi1508 you can get your issues solved in vc on discord. There are many mentors there who will be happy to help. And you can also ask Karthik if he is available so that we can discuss it and solve the issue if yo have any doubt.

**Comment by parshvi1508** [comment]
@techy4shri 
I am unable to resolve this and would not like to drag it further.
Sorry for the inconvenience caused.

**Comment by techy4shri** [comment]
@parshvi1508 thank you for informing us. Apology accepted although I hope you got yoir doubts cleared, I look forward to a contribution from you in future.

**Comment by Sai-ganesh-0004** [comment]
Can I try

**Comment by techy4shri** [comment]
@Sai-ganesh-0004 you can. You have 1 week to complete this task and raise a PR.

**Comment by Kota-Karthik** [comment]
@Sai-ganesh-0004 
any updates ?

**Comment by Sai-ganesh-0004** [comment]
> @Sai-ganesh-0004 any updates ?

going to raise pr tomorrow
