### ISSUE TITLE
 improving the README file

### ISSUE THREAD

**Issue by adityakalburgi** [Kota-Karthik/twinTrim#40]
Hi!
I'd like to contribute by improving the README file. Could you please assign this issue to me? also add labels of gssoc-ext and hacktoberfest Thanks!

**Comment by Kota-Karthik** [comment]
@adityakalburgi 
You can do it !
But before updating make sure that you understand the working of CLI tool 
So that every detail can be precise!

**Comment by Shalinis19137** [comment]
I would like to work on issue #40 in the Improving the README file repository. Could you please assign it to me? Thankyou

**Comment by Kota-Karthik** [comment]
@Shalinis19137 
This issue is assigned to someone else already 
So, it would be great if you can check our other open issues and can work on them!
