### ISSUE TITLE
i want to add text file where details explanation of codes

### ISSUE THREAD

**Issue by ragineedarade** [Kota-Karthik/twinTrim#46]

**Comment by Kota-Karthik** [comment]
so you basically want to write documentation of the project?
am i correct? @ragineedarade

**Comment by Kota-Karthik** [comment]
@ragineedarade 
You can do it but try to make it very concise how the project exactly works 
You can make a PR 
but it may or may not be merged or might require many changes

**Comment by ragineedarade** [comment]
Thank you

**Comment by ragineedarade** [comment]
Can you add gssoc level

**Comment by techy4shri** [comment]
@ragineedarade after 2 more days, this issue will either be closed or open for claim once again so I suggest raising a PR ASAP.

**Comment by keerthana2-005** [comment]
@techy4shri id like to work on this

**Comment by techy4shri** [comment]
> @techy4shri id like to work on this

You can work on it @keerthana2-005 , but as Karthik said earlier, it will depend on how you write the doc whether or not it will be merged. So please conduct proper research and get started!

**Comment by techy4shri** [comment]
@ragineedarade If you close this once more, be sure that this will reflect poorly on you.

**Comment by techy4shri** [comment]
@keerthana2-005 you are assigned now.

**Comment by techy4shri** [comment]
@keerthana2-005 kindly confirm whether you are working on this or not. You have 2 days to reply otherwise I will be closing this issue.

**Comment by keerthana2-005** [comment]
@techy4shri I am working on this .I have been lil busy it will be done within 2 to 3 days

**Comment by techy4shri** [comment]
@keerthana2-005 okay!

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..

**Comment by techy4shri** [comment]
@SaanyaGarg5 This is your second warning. Be advised that we treat contribution guidelines and the rules of GSSoC with utmost importance. Anymore violation and you'll be liable to face further consequences, including but not limited to ban from the repository and the GSSoC program.

**Comment by techy4shri** [comment]
@keerthana2-005 update please. If you do not raise a PR by tomorrow, I will be closign this issue.

**Comment by Kota-Karthik** [comment]
@keerthana2-005 any updates?

**Comment by Soumili-Saha** [comment]
I would like to work on this issue

**Comment by Swathireddy-22** [comment]
@Kota-Karthik  please assign it to me. I would like to work on it

**Comment by Kota-Karthik** [comment]
@keerthana2-005 
I am unassigning you 
@Soumili-Saha 
You can do it but try to make it very concise how the project exactly works
You can make a PR
but it may or may not be merged or might require many changes
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by techy4shri** [comment]
@Kota-Karthik I think we can close this issue after this even if someone doesn't make a proper PR.

**Comment by Swathireddy-22** [comment]
@techy4shri please assign to me.

**Comment by Kota-Karthik** [comment]
> @Kota-Karthik I think we can close this issue after this even if someone doesn't make a proper PR.

@techy4shri If @Soumili-Saha fails to raise a proper PR within 2-3 days 
we will close this issue!

**Comment by Kota-Karthik** [comment]
> @techy4shri please assign to me.

@Kota-Karthik 
This issue is already assigned to someone else 
Here we follow a strict FCFS policy acc to which @Soumili-Saha was assigned
please do not comment under any assigned issue

**Comment by Kota-Karthik** [comment]
@Soumili-Saha 
I am closing this issue!
