### ISSUE TITLE
Write Tests for Handling Missing Files in `add_or_update_file`

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#5]
- **Description**: Write tests for `add_or_update_file` that simulate cases where a file doesn't exist. The function should handle these cases gracefully, avoiding crashes or incorrect metadata.
   - **Resources**: Use the [pytest guide](https://docs.pytest.org/en/stable/getting-started.html) for setting up test cases with `FileNotFoundError` handling.
   - **Path**: `twinTrim/dataStructures/allFileMetadata.py`
   - **Code to be added**: `tests`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests.

**Comment by eleensmathew** [comment]
Can I work on this?

**Comment by Kota-Karthik** [comment]
@eleensmathew Yes, 
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by Shalinis19137** [comment]
By using File System , I can resolve this problem

**Comment by Kota-Karthik** [comment]
hey @Shalinis19137 
Its already assigned to someone else
You can work on our other open issues!
