### ISSUE TITLE
Code_Of_Conduct.md not there in the repository

### ISSUE THREAD

**Issue by ShirshenduR** [Kota-Karthik/twinTrim#54]
What documentation needs to be updated?
The Code of Conduct documentation for the twinTrim repository.

Describe the changes needed -:

> Add a more detailed Enforcement Guidelines section that clearly outlines how violations of the Code of Conduct will be reported, investigated, and resolved.

> Remove any specific maintainer email in the Reporting Violations section to make it generic for all contributors.

> Ensure that the documentation includes sections on consequences for unacceptable behavior, the right to appeal, confidentiality, and protection from retaliation.

Additional context - :

> The Code of Conduct should follow a recognized standard such as the Contributor Covenant, but be customized for the twinTrim project.

> The goal is to provide clarity on how reports of misconduct will be handled, ensuring contributors understand the process and their rights within the community.
Please assign me this issue so I can add it. Please add gssoc ext and hacktoberfest labels

**Comment by ShirshenduR** [comment]
Please assign me this issue so I can add it. Please add gssoc ext and hacktoberfest labels

**Comment by harshitpathak528** [comment]
I go through your code base and I want to work on this can you assign this to me.

**Comment by techy4shri** [comment]
@harshitpathak528 this issue is already assigned to someone else, kindly go raise your own issues.

**Comment by ShirshenduR** [comment]
I have again changed the file please check @techy4shri

**Comment by ShirshenduR** [comment]
Add the labels
