### ISSUE TITLE
 Error Handling

### ISSUE THREAD

**Issue by Ankush0286** [Kota-Karthik/twinTrim#56]
**Describe the bug**
The application does not handle exceptions during file processing. If a file cannot be accessed or processed due to permission issues or if the file is in use, the program crashes without providing informative feedback to the user.

**To Reproduce**
1. Place a file in the directory that the application is set to scan that is currently open in another program (e.g., a text editor).
2. Run the application to scan the directory for duplicates.
3. Observe that the application crashes without any error message being displayed.

**Expected behavior**
The application should handle errors gracefully by catching exceptions and providing a meaningful error message to the user, indicating which file caused the error and what type of error occurred (e.g., "Permission denied" or "File in use").

**Additional context**
This issue affects the user experience significantly, as users are left without guidance on what went wrong. Implementing error handling would improve the robustness of the application and help users troubleshoot issues more effectively.

**Comment by Ankush0286** [comment]
@Kota-Karthik, as a participant in Girls Script Summer of Code (GSSOC), I'd like to work on this issue. Could you please assign it to me and add the GSSOC level?

**Comment by Kota-Karthik** [comment]
@Ankush0286 
Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.
