### ISSUE TITLE
Assign me to add contribution guidelines to this project

### ISSUE THREAD

**Issue by ag21o9** [Kota-Karthik/twinTrim#57]
I would like to add the contribution guidelines for making PRs

**Comment by Kota-Karthik** [comment]
@ag21o9 
Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.
You can go on with it, but don't just add contribution guidelines for making PR's, but add a complete contribution guidelines 
Make sure to create a `Contribution.MD` file and link it in the `Readme.MD`

**Comment by ag21o9** [comment]
Okk I will make sure to add the things as mentioned.

**Comment by ManyashreeN** [comment]
Hi! I'd like to contribute to this issue.
Could you please assign it to me?

**Comment by Rashigera** [comment]
Hi I would like to be part of it ,could you assign this to me

**Comment by techy4shri** [comment]
@Rashigera @ManyashreeN this issue is completed.
