### ISSUE TITLE
[Feature] addition of dry run mode

### ISSUE THREAD

**Issue by adityakalburgi** [Kota-Karthik/twinTrim#58]
I can Introduce a --dry-run option to simulate deletion, allowing users to see what would be removed without actually deleting anything.
this may enhance the project please assign me to add this.

**Comment by Kota-Karthik** [comment]
@adityakalburgi 
Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.
Also update readme.md with `--dry-run` functionality

**Comment by adityakalburgi** [comment]
Hi! @Kota-Karthik submitted a PR, please have a look!

**Comment by adityakalburgi** [comment]
@Kota-Karthik can you please explain what the issue is?

**Comment by Kota-Karthik** [comment]
@adityakalburgi 
check the reviews i left at PR

**Comment by techy4shri** [comment]
@adityakalburgi kindly update your progress as per the review on your PR and whether you're working on it or not.

**Comment by adityakalburgi** [comment]
@Kota-Karthik yes i am working on it

**Comment by Kota-Karthik** [comment]
@adityakalburgi  Let me know when you finish working on it 
if you have any doubts 
ping me or @techy4shri over discord

**Comment by adityakalburgi** [comment]
ok sure!

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..

**Comment by techy4shri** [comment]
@SaanyaGarg5 No. Review the contribution guidelines again as this comment is a clear violation of one of the rules.
Consider this your first warning, anymore comment on already assigned issues and you will face severe consequences.

**Comment by SaanyaGarg5** [comment]
> @SaanyaGarg5 No. Review the contribution guidelines again as this comment is a clear violation of one of the rules. Consider this your first warning, anymore comment on already assigned issues and you will face severe consequences.

As this issue was assigned 2 weeks ago.. so I replied that I can do that  and solve the issue.. if u don't want to assign then don't do...

**Comment by techy4shri** [comment]
@SaanyaGarg5 you will take that tone back right now. Do not try to ignore the errors of your ways. You are commenting on an already assigned issue, read the latest comments. Clear disregard of code of conduct and contribution guidelines will further add to your list of violations an result in consequences.

**Comment by SaanyaGarg5** [comment]
Ok sorry next time I will not..

**Comment by adityakalburgi** [comment]
hi @Kota-Karthik and @techy4shri i checked the code everything is running absolutely fine the dry run feature is running effectively i checked the output by creating a duplicate file in my directory, its giving the output which i expected because the dry run feature will just which file will be deleted...
here is the output screenshot:
![Screenshot 2024-10-17 194025](https://github.com/user-attachments/assets/32495817-bf37-4074-960d-d92723ba846c)

**Comment by techy4shri** [comment]
check for any branch conflicts, and resolve them.

**Comment by techy4shri** [comment]
@adityakalburgi make sure to raise a new PR as the earlier one might have too many conflicts. Please raise a new PR by tomorrow and wait for review.

**Comment by adityakalburgi** [comment]
> @adityakalburgi make sure to raise a new PR as the earlier one might have too many conflicts. Please raise a new PR by tomorrow and wait for review.

Ok sure

**Comment by adityakalburgi** [comment]
Hi! @techy4shri i have submitted a new PR have a look! thank you..

**Comment by SparshKhanna0001** [comment]
@adityakalburgi @techy4shri why is this still open?

**Comment by techy4shri** [comment]
@SparshKhanna0001 this issue is still open because the PR submitted has yet to make the necessary changes as per the contributing guideline and other suggestions as per the PA's review.

**Comment by adityakalburgi** [comment]
Hi @techy4shri have a look to New PR thank you!
