### ISSUE TITLE
[Documentation Request: Add Index Page]

### ISSUE THREAD

**Issue by GUNJESH843** [Kota-Karthik/twinTrim#65]
#### **What documentation needs to be updated?**
The project's documentation needs an index page to provide users with a clear overview of the structure and contents.

#### **Describe the changes needed**
An index page should be added at the beginning of the documentation, listing key sections with links to corresponding parts of the document. Each section, such as "Introduction," "Installation," "Usage," "API Reference," and "Contributing," should be hyperlinked for easy navigation.

#### **Additional context**
The index page will improve the user experience by making it easier to navigate through the project documentation.

**Comment by GUNJESH843** [comment]
HI,
I am a gssoc-extd contributer,

can you assign me the issue,

thankyou.

**Comment by Vikas9161-trust** [comment]
We have to work on this project

**Comment by GUNJESH843** [comment]
@Vikas9161-trust 
once please confirm with @techy4shri 
I don't want to waste my time creating a pr that gets rejected without reason, even when it is asked to do by the project admin/collaborators them selfs.....

**Comment by GUNJESH843** [comment]
@techy4shri now I am being asked to reopen the issue which you closed as unplanned

**Comment by techy4shri** [comment]
@GUNJESH843 I might have mistakenly opened this. Apologies. Although what I can tell you is that if you make another pr for this, this time just for independent in readme, it can be considered.

**Comment by Wahid7852** [comment]
@GUNJESH843 any update on your PR?

**Comment by techy4shri** [comment]
@GUNJESH843 If you do not answer then I will be closing this and this issue won't be opened again.

**Comment by Kota-Karthik** [comment]
@techy4shri @GUNJESH843 
I am closing this issue!
