### ISSUE TITLE
[Feature] Logging

### ISSUE THREAD

**Issue by Kritika75** [Kota-Karthik/twinTrim#69]
Implementing logging in your code can significantly enhance its functionality, maintainability, and overall performance. Here are the main benefits of implementing logging in your duplicate file management application: Error Tracking, Audit Trail, Performance Monitoring, User Feedback, Debugging Aid, and Flexible Logging Levels.

Can you assign me this under GSSoC'24 extd. program

Thank you

**Comment by Kota-Karthik** [comment]
Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by Kritika75** [comment]
Noted, thank you.

**Comment by Kritika75** [comment]
Please also add the level labels

**Comment by Kritika75** [comment]
@Kota-Karthik can you close this issue now if everything is fine
thank you :)
