### ISSUE TITLE
Write Unit Tests for `insert_file` Method

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#7]
- **Description**: Write unit tests to validate the `insert_file` method in the `FileMetadata` class. Test cases should include:
     - Inserting a new file into the metadata list.
     - Trying to insert a file that is already present.
   - **Resources**: Refer to the [pytest getting started guide](https://docs.pytest.org/en/stable/getting-started.html) for setting up tests.
   - **Path**: `twinTrim/dataStructures/fileMetadata.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

**Comment by SandyK1002** [comment]
Hello, can I work on this issue?

**Comment by Kota-Karthik** [comment]
@SandyK1002 Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by hemantchilkuri** [comment]
Plz assign this issue  to me

**Comment by Kota-Karthik** [comment]
@hemantchilkuri 
you can work on this 
whoever raises a correct PR first 
I will merge their PR

**Comment by Kota-Karthik** [comment]
@SandyK1002 
I am unassigning you 
@hemantchilkuri 
you can work on this!

**Comment by Sai-ganesh-0004** [comment]
I would like to contribute to this < Can you Please assign me this

**Comment by harshitpathak528** [comment]
Can you assign to me.

**Comment by tarunkumar2005** [comment]
@Kota-Karthik I can work on this issue assign this to me under gssoc 2024 ext and hacktoberfest

**Comment by techy4shri** [comment]
@Sai-ganesh-0004 you can work on this issue.

**Comment by JahnaviDhanaSri** [comment]
Hello can you please assign this issue to me
