### ISSUE TITLE
[Documentation] Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by Shariq2003** [Kota-Karthik/twinTrim#78]
**What documentation needs to be updated?**
We can add all the contributor's photos in Readme file as a token of appreciation for their work.

Please assign this to me.

![image](https://github.com/user-attachments/assets/24846984-f3d2-44a4-8d2b-2a5025d1ceb9)
Like this

**Describe the changes needed**
To showcases a token of appreciation to all contributors for their hard work.

**Comment by Wahid7852** [comment]
what is the use of adding it to the readme?
i can see it on the right hand side already.
![image](https://github.com/user-attachments/assets/02094388-dd17-44ad-b102-25ff2b8a0596)

**Comment by Shariq2003** [comment]
> what is the use of adding it to the readme? i can see it on the right hand side already. ![image](https://private-user-images.githubusercontent.com/63857471/373880436-02094388-dd17-44ad-b102-25ff2b8a0596.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNDAwMTEsIm5iZiI6MTcyODEzOTcxMSwicGF0aCI6Ii82Mzg1NzQ3MS8zNzM4ODA0MzYtMDIwOTQzODgtZGQxNy00NGFkLWIxMDItMjVmZjJiOGEwNTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA1VDE0NDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNzZmODkyMDRkZTBkOWY3ODViODJmYWFiOWRiYWFmZGU3Yjc4NmM3NTkzZDg5ZGFkZWJjYzQ4MmM1MTkzYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RbSJvK9kgO2sKVTfF2mfWhB0OXdMJNl7LS0CJf5F28Y)


yes, all the contributors all listed on right hand side but there is no appreciation for them also not all the contributors photos are listed on the right hand side, that's why a special thank to all contributors is needed.

**Comment by Kota-Karthik** [comment]
@Shariq2003 
I dont really this issue is needed

**Comment by Shariq2003** [comment]
okay, np
