### ISSUE TITLE
Write Unit Tests for `add_or_update_normal_file` method

### ISSUE THREAD

**Issue by Kota-Karthik** [Kota-Karthik/twinTrim#8]
- **Description**: Write unit tests for the `add_or_update_normal_file` function. Test cases should include:
     - Adding a new file to an empty `normalStore`.
     - Updating an existing file's metadata when a duplicate file (same hash) is found.
     - Ensuring the file is correctly inserted in the metadata list without duplication.
   - **Resources**: Follow the [pytest getting started guide](https://docs.pytest.org/en/stable/getting-started.html) for writing tests.
   - **Path**: `twinTrim/dataStructures/fileMetadata.py`
   - **Note**: Ensure to maintain the file structure as per the existing files and tests, and add these tests.

**Comment by Varun-malviya5** [comment]
hii @Kota-Karthik , please can you assign me this.

**Comment by Kota-Karthik** [comment]
@Varun-malviya5 Yes,
make sure to create a separate branch before making the necessary changes and retain the folder structure.

**Comment by STSonyThomas** [comment]
Hey you mind if I work on this? Can get it done by tomorrow.

**Comment by kushwxha** [comment]
hey @Kota-Karthik, can you please assign it to me??

**Comment by Kota-Karthik** [comment]
@STSonyThomas @kushwxha 
We follow a FCFS policy here 
you can check out our other open issues or you can create new issues and get them assigned
@Varun-malviya5 is currently working on this

**Comment by techy4shri** [comment]
@Varun-malviya5 are you working on this?

**Comment by Kota-Karthik** [comment]
@Varun-malviya5 I am unassigning you and assigning this issue to @STSonyThomas
@STSonyThomas 
make sure to create a separate branch before making the necessary changes and retain the folder structure.
