### ISSUE TITLE
[Documentation] Updated Readme

### ISSUE THREAD

**Issue by akhandpratap18** [Kota-Karthik/twinTrim#81]
**What documentation needs to be updated?**
Readme file

**Describe the changes needed**
Guys your readme file is very monotonous and it might not attract better contributors to your repo. I have recently made two level 2 contributions by editting the readme file. Assign me and I'll fix it for you 
@Kota-Karthik

**Comment by techy4shri** [comment]
No readme contributions allowed. We are not looking to attract contributors here, and kindly refrain from downtalking about the repository if you want to contribute here.

**Comment by Wahid7852** [comment]
> I wasn't down talking. It was just a suggestion and I have no interest of working with people with this attitude. THANKS.

1. It is not attitude.
2. If contributors are gonna work on a project based on how ATTRACTIVE its readme is, rather than focusing on the functionality of the project, they're done.
3. Youre welcome and Good day to you
