### ISSUE TITLE
[Feature] Implementing Duplicate File Recovery System

### ISSUE THREAD

**Issue by Kishore007raj** [Kota-Karthik/twinTrim#82]
Currently, when duplicate files are detected and deleted, they are permanently removed from the user's system. Users may want to recover mistakenly deleted files, but there is no existing mechanism for this recovery, leading to data loss.

The solution I am considering for the TwinTrim application is to implement a duplicate file recovery system that moves deleted files to a temporary "bin" folder, allowing users to restore them within 30 days.

Additionally, implementing an "Undo" feature after deletion could be a good choice; however, one drawback is that it may not be practical for users who want to delete multiple duplicates at once.

I want to work on this issue and Implementing this feature would greatly enhance the usability and safety of the TwinTrim application

**Comment by anushka4124** [comment]
### Add Fuzzy Matching Feature to Enhance Duplicate Detection

I would like to propose a new feature to enhance the duplicate detection capabilities of TwinTrim by introducing fuzzy matching technique. Currently, the tool relies on strict hashing to identify duplicate files, which works well for exact duplicates. However, many users might encounter near-duplicate files—files that are not identical but share high content similarity (e.g., different versions of documents, edited images).

**The fuzzy matching feature would:**

- Use similarity metrics (such as Jaccard index or Levenshtein distance) to detect files with slight differences.
- Help identify near-duplicates, reducing redundancy and improving storage efficiency.
- Allow users to set a similarity threshold to control the sensitivity of the fuzzy matching.

I have already implemented an initial version of this feature by creating a new fuzzy.py file. This includes a method find_fuzzy_duplicates that uses fuzzy matching to detect near-duplicates.

**Comment by techy4shri** [comment]
This is a CLI based python package, not an app.

**Comment by techy4shri** [comment]
This is a python package, so if you can somehow explain an approach where the deleted fil
