### ISSUE TITLE
Improve User Experience by Implementing Multi-Select

### ISSUE THREAD

**Issue by fluid111** [Kota-Karthik/twinTrim#88]
Currently , when duplicate files are found  in CLI, users can only select files using "space" key , which will only work for the first line and to select  other files we have to  use "a" key .This limitation make it difficult to select files as user need .

To enhance the user experience, i will be  implementing a more flexible selection feature that allows users to select any file at any time.

Benefits:
-Increased Flexibility: Users can quickly select multiple files as user intend to.
-Efficiency: This change would streamline the workflow, enabling users to manage their duplicate files more effectively.
-User-Friendly Interface: A more intuitive selection method would improve overall user satisfaction with the tool.

**Comment by techy4shri** [comment]
This is a CLI based package, explain how you will implement this.

**Comment by fluid111** [comment]
For now "beaupy 'is being used for handling the selection . I am intending to use another module "inquirer' which will give the options to select the file by no. of index

**Comment by techy4shri** [comment]
@Kota-Karthik can you look at this?

**Comment by Kota-Karthik** [comment]
@fluid111 
Can you show something which you made using inquirer 
So that we can have an idea, how you will improve user experience?

**Comment by fluid111** [comment]
I have not made but  after searching which will be suitable for this work i found it and i will be learning and implementing it

**Comment by Kota-Karthik** [comment]
@fluid111 
Could you please provide us with a resource or link that supports your issue? Once we have that, I'll be able to officially assign the issue to you. Alternatively, you can still work on this, but the merging of your code changes will depend on how much they help improve the user experience.

**Comment by Wahid7852** [comment]
@fluid111 any updates on your supporting resources?
