### ISSUE TITLE
[Documentation]  update readme file

### ISSUE THREAD

**Issue by Ek-ta-bharti** [Kota-Karthik/twinTrim#90]
I want to improve the repository by adding a 'Contributor' section and including images of all those who have contributed. Please grant me permission to do this.
![Screenshot 2024-10-07 180345](https://github.com/user-attachments/assets/ac255cc1-2bc0-4f15-9bbf-9f529f8e343a)

**Comment by techy4shri** [comment]
We do not accept anymore readme contrubutions.
