### ISSUE TITLE
[Bug] Improving the structure and formats of the existing codes

### ISSUE THREAD

**Issue by ezDecode** [Kota-Karthik/twinTrim#94]
**Describe the bug**
I noticed some complexities in your codebase and would like to contribute to improving it, particularly regarding time and space complexity. I have advanced Python skills and would love the opportunity to help.

**Additional context**
And consider giving it a Level some other labels also!

**Comment by ezDecode** [comment]
@Kota-Karthik Consider it!

**Comment by techy4shri** [comment]
Explain what time and space complexities did you notice.

**Comment by ezDecode** [comment]
Like the codes are not formatted properly or not written in a structured
way ... And I'm sure that I can fix it.

**Comment by techy4shri** [comment]
Give context, explain a part where you noticed the issue, we cannot accept anything without proper details.
Add a snippet of code in the comment where you believe the code is not structured or could be improved and then expain your approach.

**Comment by ezDecode** [comment]
Okay I'll send the details by evening I'm in class right now

**Comment by Kota-Karthik** [comment]
@ezDecode 
Give context, explain a part where you noticed the issue, we cannot accept anything without proper details.
Add a snippet of code in the comment where you believe the code is not structured or could be improved and then expain your approach.

**Comment by ezDecode** [comment]
Like I can update the code documentation what happening in the code ....How to code works so that every one can understand!!

**Comment by techy4shri** [comment]
You changed your comment @ezDecode Earlier you were mentioned time and space complexities, now you're talking about documentation. 
This is your first warning, do not raise an issue simply for the sake of it. Find plausible issues and check whether someone else has raised a similar one earlier before raising one.
This issue will not be assigned.

Ignore this warning, and you'll face consequences.

**Comment by ezDecode** [comment]
Just close it!!
